runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/?
  static_files: www/index.html
  upload: www/index.html
  login: admin
- url: /static
  static_dir: www/static
- url: /api/admin/.*
  script: main.app
  login: admin
- url: /api/.*
  script: main.app
- url: /.*
  static_files: www/index.html
  upload: www/index.html

automatic_scaling:
  max_concurrent_requests: 24
  max_idle_instances: 2
  min_idle_instances: 0
  min_pending_latency: 400ms
