runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /admin/?
  static_files: www/index.html
  upload: www/index.html
  login: admin
  secure: always
  redirect_http_response_code: 301
- url: /static
  static_dir: www/static
  secure: always
  redirect_http_response_code: 301
- url: /api/admin/.*
  script: main.app
  login: admin
  secure: always
  redirect_http_response_code: 301
- url: /api/.*
  script: main.app
  secure: always
  redirect_http_response_code: 301
- url: /.*
  static_files: www/index.html
  upload: www/index.html
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  max_concurrent_requests: 24
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1000ms
  max_pending_latency: 5000ms
